import streamlit as st
from database import get_connection
import numpy as np


def assessment_history():

    
    # -----------------------------
    # AUTH CHECK
    # -----------------------------
    user = st.session_state.get("user")

    if not user:
        st.error("Session expired. Please login again.")
        st.stop()

    login_id = user["id"]
    username = user["username"]
    company_name = user["company_name"]

    st.markdown("##  Performance Insights")
    st.caption("Long-term risk trends and strategic analysis")
    st.markdown("---")

    # -----------------------------
    # FETCH DATA
    # -----------------------------
    conn = get_connection()
    cursor = conn.cursor()

    data = cursor.execute("""
    SELECT datetime(created_at, '+5 hours', '+30 minutes') as created_at,
       digital_score,
       human_score,
       financial_score,
       governance_score,
       overall_score,
       risk_level
    FROM assessments
    WHERE login_id = ?
    ORDER BY created_at DESC
    """, (login_id,)).fetchall()

    conn.close()

    # -----------------------------
    # NO DATA
    # -----------------------------
    if not data:
        st.info("No assessments found. Please create one first.")
        st.stop()

    # -----------------------------
    # EXTRACT DATA
    # -----------------------------
    scores = [row["overall_score"] for row in data]
    digital = [row["digital_score"] for row in data]
    human = [row["human_score"] for row in data]
    financial = [row["financial_score"] for row in data]
    governance = [row["governance_score"] for row in data]

    # -----------------------------
    # TREND VISUAL
    # -----------------------------
    st.markdown("###  Risk Trend Over Time")
    st.line_chart(scores)

    # -----------------------------
    # TREND ANALYSIS
    # -----------------------------
    st.markdown("###  Trend Analysis")

    if len(scores) > 1:
        change = scores[-1] - scores[0]

        if change > 5:
            st.error(f" Risk increased by {change:.2f} over time — declining performance")
        elif change < -5:
            st.success(f" Risk decreased by {abs(change):.2f} — improvement observed")
        else:
            st.info(" Risk remains relatively stable")

    # -----------------------------
    # PATTERN DETECTION
    # -----------------------------
    st.markdown("###  Pattern Detection")

    patterns = []

    if max(scores) - min(scores) > 20:
        patterns.append("️ High volatility detected in risk levels")

    if all(x > 60 for x in scores[-3:]) and len(scores) >= 3:
        patterns.append(" Consistently high risk in recent assessments")

    if all(x < 40 for x in scores[-3:]) and len(scores) >= 3:
        patterns.append(" Consistently low risk — strong control environment")

    if scores[-1] > scores[-2] if len(scores) > 1 else False:
        patterns.append(" Latest assessment shows increasing risk trend")

    if not patterns:
        patterns.append(" No concerning patterns detected")

    for p in patterns:
        st.write(p)

    # -----------------------------
    # DIMENSION ANALYSIS
    # -----------------------------
    st.markdown("###  Dimension Performance")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Digital Avg", f"{np.mean(digital):.2f}")
    col2.metric("Human Avg", f"{np.mean(human):.2f}")
    col3.metric("Financial Avg", f"{np.mean(financial):.2f}")
    col4.metric("Governance Avg", f"{np.mean(governance):.2f}")

    # -----------------------------
    # STRATEGIC RECOMMENDATIONS
    # -----------------------------
    st.markdown("###  Strategic Recommendations")

    recommendations = []

    if np.mean(digital) < 50:
        recommendations.append("Improve digital infrastructure and security controls")

    if np.mean(human) < 50:
        recommendations.append("Increase employee awareness and training programs")

    if np.mean(financial) < 50:
        recommendations.append("Strengthen financial risk planning and reserves")

    if np.mean(governance) < 50:
        recommendations.append("Enhance governance policies and compliance monitoring")

    if max(scores) - min(scores) > 20:
        recommendations.append("Stabilize risk fluctuations through consistent controls")

    if not recommendations:
        recommendations.append("Maintain current strategies — performance is stable")

    for r in recommendations:
        st.warning(" " + r)

    # -----------------------------
    # DATA TABLE (OPTIONAL)
    # -----------------------------
    st.markdown("###  Historical Records")
    st.dataframe(data, use_container_width=True)

    # -----------------------------
    # FOOTER
    # -----------------------------
    st.markdown("---")
    st.caption("Generated by IRIS – Institutional Risk Intelligence System")
